services:
  bitrix-lead-alert-bot:
    build: .
    container_name: bitrix-lead-alert-bot
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
